### PR TITLE
optionally allow nulls to pass through to the DynamicImageLoader

### PR DESCRIPTION
**Pull request by dbachelder**

### CODE REVIEW

**Comment by amigold** [comment]
Thanks again. I must ask, why is this needed?

**Comment by dbachelder** [comment]
When the row recycles and the next row doesn't have an image in the data item I need to show a placeholder. But right now the last image stays put when the string extractor extracts null.

**Comment by dbachelder** [comment]
Previously I was handing back a "special" string value from the extractor and looking for that in the image loader... But that seemed hacky... I'm open to other solutions for this...

**Comment by dbachelder** [comment]
At one point I added a default static image loader... But it seemed so verbose... Then I thought of adding a default resource id... But that seemed too opinionated... So ultimately I landed here with the dynamic loader deciding what to do with nulls

**Comment by amigold** [comment]
Good catch! That's an interesting issue. 

I think that if we allow nulls to reach the Dynamic image loader, we assume that it can handle nulls efficiently. We also assume that you can configure your loader implementation to load placeholder images. 

Maybe the best way is to let you provide a fallback static image loader so it's not a default requirement, but can still be added if needed. 

What do you think?

**Comment by dbachelder** [comment]
I think by forcing the client to specifically indicate that it expects nulls by calling this new method we account for those eventualities. I originally implemented it as you suggest but it just seemed to add too much boilerplate to my code for such a simple and expected condition (at least in our listview) that I went with this "simpler" approach.  It's your project and I don't have a strong opinion either way.. so I'm happy to reimplement the static image loader strategy if you like that better.

**Comment by amigold** [comment]
I think you're absolutely right. By explicitly allowing nulls we can allow developers to handle nulls themselves in the DynamicImageLoader implementation without writing even more boilerplate (Java has enough of that as it is)

Again, thanks a lot for the additions and input!

**Pull request merged**
